### ISSUE TITLE
No favicon. Can't parse '-'

### ISSUE THREAD

**Issue by Purfview** [retonato/torrenthistory-public#13]
Nice project! I added site to https://github.com/Purfview/IMDb-Scout-Mod/commit/77ee7adeaace7d77380e765a517cbb966288358a

Few small issues:
No favicon.
Site can't parse titles like "Ant-man".

PS:
Would be nice if both 'word' & 'created' search operators could work together.

**Comment by retonato-temp** [comment]
Hi @Purfview , sorry for the late reply, I'm travelling.

1. There was a favicon some time ago, it seems that I accidentally removed it afterwards. I will return it when I'm back (in 2 weeks or so).
2. When you search for words - only alphanumeric characters are acceped. So you either need to search for 2 separate words (without a dash) or search for the exact name or its prefix using "name" keyword (name:ubuntu*). Having said that, I will probably need to change the code, so that all characters are accepted for word search.
3. You can use all keywords, supported by the target. For example: https://torrenthistory.org/search?order=desc&sort_by=created&q=ubuntu+server+created%3C2019+size%3E1g&target=torrents

**Comment by retonato** [comment]
Ok, favicon is added.
